# Generated by Django 5.0.2 on 2024-04-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_remove_categories_test_alter_categories_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="cat",
            field=models.CharField(
                default="Не выбрано", max_length=255, verbose_name="Категория"
            ),
        ),
    ]
