# Generated by Django 5.0.2 on 2024-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_categories_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="logo",
            field=models.ImageField(default="hui", upload_to="img/"),
        ),
    ]
