# Generated by Django 5.0.2 on 2024-04-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_categories_logo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Columns",
        ),
        migrations.DeleteModel(
            name="Computers",
        ),
        migrations.DeleteModel(
            name="Notebooks",
        ),
        migrations.DeleteModel(
            name="Phones",
        ),
        migrations.DeleteModel(
            name="Tablets",
        ),
        migrations.DeleteModel(
            name="Tvs",
        ),
        migrations.AlterField(
            model_name="categories",
            name="logo",
            field=models.ImageField(default="Не выбрано", upload_to="img/"),
        ),
    ]
