# Generated by Django 5.0.2 on 2024-05-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_products_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="camera",
            field=models.CharField(
                default="Не выбрано", max_length=255, verbose_name="Камера"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="color",
            field=models.CharField(
                default="Не выбрано", max_length=255, verbose_name="Цвет"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="display",
            field=models.CharField(
                default="Не выбрано", max_length=255, verbose_name="Дисплей"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="processor",
            field=models.CharField(
                default="Не выбрано", max_length=255, verbose_name="Процессор"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="ram",
            field=models.CharField(
                default="Не выбрано", max_length=255, verbose_name="Оперативная память"
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="rom",
            field=models.CharField(
                default="Не выбрано", max_length=255, verbose_name="Встроенная память"
            ),
        ),
    ]
